# RecImpute - A Recommendation System of Imputation Techniques for Missing Values in Time Series,
# eXascale Infolab, University of Fribourg, Switzerland

# imputebenchlabeler_config.yaml
# @author: @chacungu

# ImputeBenchLabeler related configuration file
# ------------------------------------

# LBL_PROPERTIES: All properties that labels can have (e.g. labels can be of type mono or multi)
LBL_PROPERTIES:
  # type: Specifies if the labels are mono or multi labels. Value can be one of: monolabels, regression, multilabels
  - type: monolabels
  # multi_labels_nb_rel: Top N algorithms to consider relevant in a multi-labels vector
  - multi_labels_nb_rel: 3 
  # reduction_threshold: For a label, if the percentage of clusters with this label is lower than this threshold,
  # the label is removed and the clusters are re-labeled with "valid" labels
  - reduction_threshold: .00

ALGORITHMS_LIST:
  - cdrec
  - dynammo
  - grouse
  - rosl
  - softimp
  - svdimp
  - svt
  - stmvl
  - spirit
  - tenmf
  - tkcm
  - trmf
  #- ssa
  #- m-rnn
  #- brits

# Benchmark config: ------------------------------------------------------------------------

# USE_BCHMK_ON_DATASET: If True uses all time series of a data set to label one sequence. Otherwise, ises only the time series from
# the same cluster as the sequence to label.
USE_BCHMK_ON_DATASET: False

# BENCHMARK_SCENARIO: scenario to use when running the ImputeBench benchmark. As of now, only miss_perc can be used.
BENCHMARK_SCENARIO: miss_perc

# BENCHMARK_ERRORS: list of errors to measure when running the ImputeBench benchmark. Can be any of mae, mse, rmse.
BENCHMARK_ERRORS:
  - mae
  - mse
  - rmse

# BENCHMARK_ERROR_TO_MINIMIZE: error to minimize when labeling the time series (algo with lowest error is used as label)
BENCHMARK_ERROR_TO_MINIMIZE: 'rmse'

# BENCHMARK_PATH: path to the Debug folder of the ImputeBench benchmark
BENCHMARK_PATH: /home/guillaume/bench-vldb20/TestingFramework/bin/Debug