# RecImpute - A Recommendation System of Imputation Techniques for Missing Values in Time Series,
# XXXXX

# trainingsets_config.yaml
# @author: @XXXXX

# Training sets related configuration file
# ------------------------------------

# RDM_SEED: Seed to use for any random operation in the TrainingSet class
RDM_SEED: 23

# DATA_PROPERTIES: All properties that can be used to specify data transformations and manipulations 
DATA_PROPERTIES:
  # balance: Specifies if the data should be balanced. Value can be one of: clusters, labels, null.
  - balance: null
  # usable_data_perc: Percentage of data to use for training (used mainly for T-Daub). Value must be within range ]0.0; 1.0].
  - usable_data_perc: 1.0
  # augment: Specifies if the data should be augmented. Value can be one of: True, False.
  - augment: False

# BALANCING_STRATEGY: Name of the balancing strategy. Value can be one of: all_same, rmv_min_reduce_max.
BALANCING_STRATEGY: rmv_min_reduce_max

# BALANCING_STRAT2_MIN_THRESHOLD: Used only for balancing strategy n°2 (rmv_min_reduce_max). Minimum percentage of class 
# attribution to keep the class.
BALANCING_STRAT2_MIN_THRESHOLD: 0.05

# BALANCING_STRAT2_MAX_THRESHOLD: Used only for balancing strategy n°2 (rmv_min_reduce_max). Maximum percentage of class 
# attribution to not downsize the class.
BALANCING_STRAT2_MAX_THRESHOLD: 0.20


# Test & validation sets config: ------------------------------------------------------------------------

# TEST_SET_RESERVATION_STRAT: strategy to select the test set's content
# can be one of: one_cluster_every_two_dataset, clusters_percentage, ts_percentage
TEST_SET_RESERVATION_STRAT: ts_percentage

# TEST_SIZE_PERCENTAGE: percentage of clusters/time series to use for testing. Only used if TEST_SET_RESERVATION_STRAT == (clusters_percentage or ts_percentage)
TEST_SIZE_PERCENTAGE: 0.35

# VALIDATION_SET_RESERVATION_STRAT: old, clusters_percentage, ts_percentage
VALIDATION_SET_RESERVATION_STRAT: ts_percentage

# VALIDATION_SIZE_PERCENTAGE: percentage of the non-test set to use for validation (25% = 20% of all data)
VALIDATION_SIZE_PERCENTAGE: 0.25

# PROB_DEC_FACTOR_AFTER_ATTRIBUTION: Factor by which divide a cluster's probability to be attributed to the training set after
# having been attributed to this set.
PROB_DEC_FACTOR_AFTER_ATTRIBUTION: 0.5