# RecImpute - A Recommendation System of Imputation Techniques for Missing Values in Time Series,
# eXascale Infolab, University of Fribourg, Switzerland

# trainingsets_config.yaml
# @author: @chacungu

# Training sets related configuration file
# ------------------------------------

# RDM_SEED: Seed to use for any random operation in the TrainingSet class
RDM_SEED: 23

# DATA_PROPERTIES: All properties that can be used to specify data transformations and manipulations 
DATA_PROPERTIES:
  # usable_data_perc: Percentage of data to use for training (used mainly for T-Daub). Value must be within range ]0.0; 1.0].
  - usable_data_perc: 1.0

# Test & validation sets config: ------------------------------------------------------------------------

# TEST_SET_RESERVATION_STRAT: strategy to select the test set's content
TEST_SET_RESERVATION_STRAT: one_cluster_every_two_dataset 
# can be one of: one_cluster_every_two_dataset, 

VALIDATION_SIZE_PERCENTAGE: 0.3